// site.config.mjs: the ONLY file that carries site identity.
//
// To run this engine for another site, change this file and the folders under
// content/. Nothing in src/, worker/, plugins/ or scripts/ should need an edit.
// Plain data only: no imports, no secrets. Analytics project keys used in the
// browser are public by design; API keys for reports come from env vars.

export default {
	origin: 'https://emin.de',
	name: 'emin.de',
	repo: 'https://github.com/eminogrande/emin-de',
	email: 'hello@emin.de',
	license: { text: 'CC BY 4.0', code: 'MIT' },

	// What this site IS, in one sentence. Used verbatim as the llms.txt opener and
	// the Organization/WebSite description. Never "<name> is a website".
	definition:
		'emin.de publishes long-form written work by Emin Mahrt on Bitcoin self-custody, payment rails, AI agents and the engineering behind them. Every post is plain Markdown in a public GitHub repository and is served as HTML, Markdown, JSON, feeds and through a public MCP server.',
	tagline: 'Long-form engineering writing, built to be read by people and agents.',
	// Home page headline per language (the big serif line under the masthead).
	hero: {
		en: 'Notes on Bitcoin, AI agents and building things.',
		de: 'Notizen über Bitcoin, KI-Agenten und das Bauen von Dingen.',
	},
	// Theme rows on the home page: label per language + the categories they pull from.
	themes: [
		{ id: 'nuri-bitcoin', label: { en: 'Nuri & Bitcoin', de: 'Nuri & Bitcoin' }, categories: ['nuri', 'bitcoin', 'payments'] },
		{ id: 'agents-ai', label: { en: 'Agents & AI', de: 'Agenten & KI' }, categories: ['agents-ai'] },
		{ id: 'building', label: { en: 'Building', de: 'Bauen' }, categories: ['building'] },
		{ id: 'science', label: { en: 'Science', de: 'Wissenschaft' }, categories: ['science'] },
		{ id: 'culture', label: { en: 'Culture', de: 'Kultur' }, categories: ['culture', 'notes'] },
	],

	// Search-console ownership proofs. Empty = no meta tag is emitted.
	verification: { google: '', bing: '' },

	// Permanent redirects (301) served by the Worker and the Node origin.
	// Keys are old paths on this host, values are paths or absolute URLs.
	// Old emino.app slugs are added automatically from each post's original_url
	// (see scripts/generate-content.mjs -> src/generated/redirects.json,
	// public/_redirects and docs/REDIRECTS-emino-app.md).
	redirects: {},

	// Primary person/publisher. Must match an author id below with type "human".
	owner: 'emin',
	// Publisher identity, used on /about, /principles and in Person/Organization schema.
	publisher: {
		name: 'Emin Mahrt',
		role: { en: 'Journalist and publisher', de: 'Journalist und Verleger' },
		jobTitle: 'Journalist, publisher',
		publication: {
			name: 'proud magazine',
			// proud.de 302-redirects to the magazine archive on Issuu (checked 2026-10-06).
			url: 'https://proud.de',
			archive: 'https://issuu.com/proud',
			note: {
				en: 'Berlin print magazine, archived in the German National Library.',
				de: 'Berliner Printmagazin, archiviert in der Deutschen Nationalbibliothek.',
			},
		},
	},
	knowsAbout: [
		'journalism and publishing',
		'independent magazines',
		'Bitcoin self-custody',
		'passkeys and WebAuthn PRF',
		'MuSig2 co-signing',
		'x402 agent payments',
		'Model Context Protocol',
		'agent-readiness engineering',
		'SEO and generative engine optimization',
		'payment rails and SEPA',
	],

	// Locales. The first one is the default and lives at the URL root; others are
	// prefixed (/de/...). A locale route only exists when content in it exists.
	locales: [
		{ code: 'en', hreflang: 'en', label: 'English', dateLocale: 'en-GB' },
		{ code: 'de', hreflang: 'de', label: 'Deutsch', dateLocale: 'de-DE' },
	],

	// Authors. type "human" = a real person. type "ai_editorial" = an openly named
	// AI desk: visibly labelled, no fake biography, no photo, always supervised by
	// a human author. Pseudonyms are only allowed as ai_editorial entries.
	// type "guest" = text by someone else, republished: the byline is the post's
	// `original_author` field; no biography, no photo, no profile page claims.
	authors: {
		emin: {
			type: 'human',
			name: 'Emin Mahrt',
			url: '/about',
			jobTitle: 'Journalist, publisher',
			sameAs: ['https://github.com/eminogrande', 'https://www.linkedin.com/in/eminmahrt', 'https://x.com/eminogrande', 'https://medium.com/@em', 'https://emin.substack.com', 'https://proud.de'],
		},
		'ai-desk': {
			type: 'ai_editorial',
			name: 'emin.de AI Desk',
			supervisor: 'emin',
			label: { en: 'AI-written, human-supervised', de: 'KI-geschrieben, von einem Menschen beaufsichtigt' },
			description: {
				en: 'An AI writing desk, not a person. Drafts are generated by language models from public sources, then checked and approved by Emin Mahrt before publication.',
				de: 'Ein KI-Schreibtisch, keine Person. Entwürfe werden von Sprachmodellen aus öffentlichen Quellen erzeugt und vor der Veröffentlichung von Emin Mahrt geprüft und freigegeben.',
			},
		},
		guest: {
			type: 'guest',
			name: 'Guest author',
			label: { en: 'Guest text, republished', de: 'Gasttext, wiederveröffentlicht' },
		},
	},

	categories: {
		nuri: { en: 'Nuri', de: 'Nuri' },
		bitcoin: { en: 'Bitcoin', de: 'Bitcoin' },
		'agents-ai': { en: 'Agents and AI', de: 'Agenten und KI' },
		building: { en: 'Building', de: 'Bauen' },
		payments: { en: 'Payments', de: 'Zahlungen' },
		notes: { en: 'Notes', de: 'Notizen' },
		science: { en: 'Science', de: 'Wissenschaft' },
		culture: { en: 'Culture', de: 'Kultur' },
	},

	formats: {
		essay: { en: 'Essays', de: 'Essays' },
		note: { en: 'Notes', de: 'Notizen' },
		explainer: { en: 'Explainers', de: 'Erklärstücke' },
		podcast: { en: 'Podcasts', de: 'Podcasts' },
		video: { en: 'Videos', de: 'Videos' },
		short: { en: 'Shorts', de: 'Shorts' },
		illustration: { en: 'Illustrations', de: 'Illustrationen' },
		changelog: { en: 'Changelog entries', de: 'Changelog-Einträge' },
		guide: { en: 'Guides', de: 'Anleitungen' },
		summary: { en: 'Summaries', de: 'Zusammenfassungen' },
		photo: { en: 'Photo posts', de: 'Fotobeiträge' },
	},

	// CORE PRINCIPLE: free speech. Nothing is hidden for its topic, its words or
	// a pending review. Every post is indexable and in the sitemap. Provenance
	// (human / mixed / AI-written) is a visible label, never a gate. The only
	// way to hide a post is `draft: true`, written by the author himself.
	// tests/engine.test.mjs fails the build if any content post is noindex.
	principles: {
		freeSpeech: true,
		footer: {
			en: 'Free speech. Nothing here is censored. AI help is labelled, the words are mine.',
			de: 'Freie Rede. Hier wird nichts zensiert. KI-Hilfe ist gekennzeichnet, die Worte sind meine.',
		},
	},

	social: {
		github: 'eminogrande',
		x: 'eminogrande',
		substack: 'https://emin.substack.com',
	},

	// Analytics: OFF by default. Neither script is emitted unless enabled here.
	// PostHog runs with cookieless_mode "always" (no cookies, no local/session
	// storage; cookieless mode must also be switched on in the PostHog project
	// settings). GA4 additionally requires the visitor's explicit opt-in on
	// /privacy before anything loads (TTDSG section 25 / GDPR).
	analytics: {
		posthog: { enabled: false, projectKey: '', apiHost: 'https://eu.i.posthog.com' },
		ga4: { enabled: false, measurementId: '' },
	},

	// Hosting target (see docs/HOSTING.md). Not secret: account ids are visible
	// in every dashboard URL. API tokens never go here.
	cloudflare: { accountId: '60aa4fd3b9c4c1c384a3234200f42672', workerName: 'emin-de' },
};
