// site.config.mjs: the ONLY file that carries site identity.
//
// To run this engine for another site, change this file and the folders under
// content/. Nothing in src/, worker/, plugins/ or scripts/ should need an edit.
// Plain data only: no imports, no secrets. Analytics project keys used in the
// browser are public by design; API keys for reports come from env vars.

export default {
	origin: 'https://emin.de',
	name: 'emin.de',
	repo: 'https://github.com/eminogrande/emin-de',
	email: 'hello@emin.de',
	license: { text: 'CC BY 4.0', code: 'MIT' },

	// What this site IS, in one sentence. Used verbatim as the llms.txt opener and
	// the Organization/WebSite description. Never "<name> is a website".
	definition:
		'emin.de publishes long-form written work by Emin Mahrt on Bitcoin self-custody, payment rails, AI agents and the engineering behind them. Every post is plain Markdown in a public GitHub repository and is served as HTML, Markdown, JSON, feeds and through a public MCP server.',
	tagline: 'Long-form engineering writing, built to be read by people and agents.',

	// Primary person/publisher. Must match an author id below with type "human".
	owner: 'emin',
	knowsAbout: [
		'Bitcoin self-custody',
		'passkeys and WebAuthn PRF',
		'MuSig2 co-signing',
		'x402 agent payments',
		'Model Context Protocol',
		'agent-readiness engineering',
		'SEO and generative engine optimization',
		'payment rails and SEPA',
	],

	// Locales. The first one is the default and lives at the URL root; others are
	// prefixed (/de/...). A locale route only exists when content in it exists.
	locales: [
		{ code: 'en', hreflang: 'en', label: 'English', dateLocale: 'en-GB' },
		{ code: 'de', hreflang: 'de', label: 'Deutsch', dateLocale: 'de-DE' },
	],

	// Authors. type "human" = a real person. type "ai_editorial" = an openly named
	// AI desk: visibly labelled, no fake biography, no photo, always supervised by
	// a human author. Pseudonyms are only allowed as ai_editorial entries.
	// type "guest" = text by someone else, republished: the byline is the post's
	// `original_author` field; no biography, no photo, no profile page claims.
	authors: {
		emin: {
			type: 'human',
			name: 'Emin Mahrt',
			url: '/about',
			jobTitle: 'Engineer and writer',
			sameAs: ['https://github.com/eminogrande', 'https://x.com/eminogrande', 'https://www.linkedin.com/in/eminmahrt'],
		},
		'ai-desk': {
			type: 'ai_editorial',
			name: 'emin.de AI Desk',
			supervisor: 'emin',
			label: { en: 'AI-written, human-supervised', de: 'KI-geschrieben, von einem Menschen beaufsichtigt' },
			description: {
				en: 'An AI writing desk, not a person. Drafts are generated by language models from public sources, then checked and approved by Emin Mahrt before publication.',
				de: 'Ein KI-Schreibtisch, keine Person. Entwürfe werden von Sprachmodellen aus öffentlichen Quellen erzeugt und vor der Veröffentlichung von Emin Mahrt geprüft und freigegeben.',
			},
		},
		guest: {
			type: 'guest',
			name: 'Guest author',
			label: { en: 'Guest text, republished', de: 'Gasttext, wiederveröffentlicht' },
		},
	},

	categories: {
		nuri: { en: 'Nuri', de: 'Nuri' },
		bitcoin: { en: 'Bitcoin', de: 'Bitcoin' },
		'agents-ai': { en: 'Agents and AI', de: 'Agenten und KI' },
		building: { en: 'Building', de: 'Bauen' },
		payments: { en: 'Payments', de: 'Zahlungen' },
		notes: { en: 'Notes', de: 'Notizen' },
		science: { en: 'Science', de: 'Wissenschaft' },
		culture: { en: 'Culture', de: 'Kultur' },
	},

	formats: {
		essay: { en: 'Essays', de: 'Essays' },
		note: { en: 'Notes', de: 'Notizen' },
		explainer: { en: 'Explainers', de: 'Erklärstücke' },
		podcast: { en: 'Podcasts', de: 'Podcasts' },
		video: { en: 'Videos', de: 'Videos' },
		short: { en: 'Shorts', de: 'Shorts' },
		illustration: { en: 'Illustrations', de: 'Illustrationen' },
		changelog: { en: 'Changelog entries', de: 'Changelog-Einträge' },
		guide: { en: 'Guides', de: 'Anleitungen' },
		summary: { en: 'Summaries', de: 'Zusammenfassungen' },
		photo: { en: 'Photo posts', de: 'Fotobeiträge' },
	},

	// Indexing policy, applied at build without touching the post files.
	// Posts whose provenance is listed here render with noindex and stay out of
	// sitemap, feeds, llms.txt and the API until a human reviews them.
	indexing: { noindexProvenance: ['mixed', 'unknown'] },

	social: {
		github: 'eminogrande',
		x: 'eminogrande',
		substack: 'https://emin.substack.com',
	},

	// Analytics: OFF by default. Neither script is emitted unless enabled here.
	// PostHog runs with cookieless_mode "always" (no cookies, no local/session
	// storage; cookieless mode must also be switched on in the PostHog project
	// settings). GA4 additionally requires the visitor's explicit opt-in on
	// /privacy before anything loads (TTDSG section 25 / GDPR).
	analytics: {
		posthog: { enabled: false, projectKey: '', apiHost: 'https://eu.i.posthog.com' },
		ga4: { enabled: false, measurementId: '' },
	},

	// Hosting target (see docs/HOSTING.md). Not secret: account ids are visible
	// in every dashboard URL. API tokens never go here.
	cloudflare: { accountId: '60aa4fd3b9c4c1c384a3234200f42672', workerName: 'emin-de' },
};
