// Redirect table: site.config.mjs `redirects` plus every old emino.app slug.
// Output feeds the Worker/Node origin (301), a Cloudflare-style _redirects
// file, and docs/REDIRECTS-emino-app.md for whoever updates emino.app.

const pathOf = (url) => {
	try {
		return new URL(url).pathname.replace(/\/+$/, '') || '/';
	} catch {
		return null;
	}
};

export function buildRedirects(posts, config) {
	const map = { ...(config.redirects || {}) };
	const emino = [];
	const ambiguous = [];
	const own = new Set(posts.map((p) => p.path));
	const reserved = new Set(['/', '/posts', '/about', '/contact', '/photos', '/archive', '/talks', '/changelog', '/developers', '/agent-ready', '/privacy']);
	const byOld = new Map();
	for (const post of posts) {
		if (!post.originalUrl || !/^https?:\/\/(www\.)?emino\.app\//.test(post.originalUrl)) continue;
		const oldPath = pathOf(post.originalUrl);
		// An index URL (/, /posts) is not a post address: never redirect it.
		if (!oldPath || oldPath.split('/').filter(Boolean).length < 2) {
			ambiguous.push({ oldPath: oldPath || post.originalUrl, targets: [`${config.origin}${post.path}`], note: 'original_url is an index page, not a post URL' });
			continue;
		}
		if (!byOld.has(oldPath)) byOld.set(oldPath, []);
		byOld.get(oldPath).push(post);
	}
	for (const [oldPath, list] of [...byOld].sort(([a], [b]) => a.localeCompare(b))) {
		if (list.length > 1) {
			// Two posts once shared one emino.app URL (e.g. "untitled-post"): no
			// automatic 301, the newest wins in the emino.app table and the rest are listed.
			const sorted = [...list].sort((a, b) => b.date.localeCompare(a.date));
			ambiguous.push({ oldPath, targets: sorted.map((p) => `${config.origin}${p.path}`) });
			emino.push({ from: `https://emino.app${oldPath}/`, to: `${config.origin}${sorted[0].path}`, post: sorted[0] });
			continue;
		}
		const post = list[0];
		emino.push({ from: `https://emino.app${oldPath}/`, to: `${config.origin}${post.path}`, post });
		// The same old path on emin.de (/posts/<old-slug>) 301s to the new slug,
		// unless it already is a real page here.
		if (oldPath !== post.path && !own.has(oldPath) && !reserved.has(oldPath) && !map[oldPath]) map[oldPath] = post.path;
	}
	return { map, emino, ambiguous };
}

export function redirectsFile(map) {
	const lines = ['# Generated by scripts/generate-content.mjs. Do not edit; change site.config.mjs `redirects` or post original_url.'];
	for (const [from, to] of Object.entries(map).sort(([a], [b]) => a.localeCompare(b))) lines.push(`${from} ${to} 301`);
	return `${lines.join('\n')}\n`;
}

export function redirectsDoc({ emino, ambiguous }, config) {
	const rows = emino.map(({ from, to, post }) => `| ${from} | ${to} | ${post.noindex ? 'noindex (awaits review)' : 'indexed'} |`);
	return `# Redirects: emino.app to emin.de

Generated by \`scripts/generate-content.mjs\` from each post's \`original_url\`. Do not edit by hand.

emin.de is the original for every post. Apply these as **301** redirects on emino.app (path-preserving, trailing slash optional). The emin.de pages already carry \`rel=canonical\` to themselves and list the emino.app URL as \`sameAs\`/\`isBasedOn\` in JSON-LD.

${emino.length} emino.app URL(s).

## Cloudflare bulk-redirect / _redirects format

\`\`\`
${emino.map(({ from, to }) => `${new URL(from).pathname} ${to} 301`).join('\n')}
\`\`\`

## Table

| emino.app URL | emin.de URL | emin.de status |
| --- | --- | --- |
${rows.join('\n')}
${ambiguous.length ? `\n## Shared old URLs (resolve by hand)\n\nThese emino.app URLs were used by more than one post, or point at an index page. Where a table row exists it points at the newest post; the rest need a decision.\n\n${ambiguous.map((a) => `- ${a.oldPath}: ${a.targets.join(', ')}${a.note ? ` (${a.note})` : ''}`).join('\n')}\n` : ''}`;
}
